apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        location / {
            return 200 "OK";
        }
        location /jenkins/ {
            proxy_pass http://localhost:8080;
                proxy_read_timeout  90;
                proxy_set_header X-Forwarded-Host $host:$server_port;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
        }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  volumes:
  - name: nginx-configs
    configMap:
      name: nginx-config
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
      - containerPort: 80
    volumeMounts:
    - name: nginx-configs
      mountPath: /etc/nginx/conf.d
  - name: jenkins
    securityContext:
      runAsUser: 1000
    image: jenkins/jenkins:lts-alpine
    ports:
    - containerPort: 8080
    env:
    - name: JENKINS_OPTS
      value: "--prefix=/jenkins"
