apiVersion: v1
kind: Secret
metadata:
  name: secret-key
type: Opaque
stringData:
  secretKey: {{secretKey}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-key
              key: secretKey
